# Generated by Django 3.1.3 on 2021-02-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210227_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='poster_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='poster_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
