# Generated by Django 3.1.8 on 2021-04-27 21:58

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_auto_20210422_2154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=authentication.models.UserUsernameField(max_length=15),
        ),
    ]
